version: '3.7'
services:
  gridgain-source-node:
    image: gridgain/enterprise:8.7.14
    container_name: gridgain-source-node
    tty: true
    environment:
      - "JVM_OPTS=-DIGNITE_QUIET=true -Xmx1G"
      - CONFIG_URI=/opt/gridgain/ext-config/gridgain-source-config.xml
      - OPTION_LIBS=ignite-rest-http
      - IGNITE_QUIET=false
    networks:
      - gridgain-net
    ports:
      #- "31100-31200"
      #- "11211"
      #- "49128"
#      - "47501:47500"
#      - "47101:47100"
      - "10800:10800"
      #- "48100-48200"
      - "6081:8080"
    volumes:
      #      - gridgain-data-1:/opt/gridgain/work
      - ./gridgain-config:/opt/gridgain/ext-config

  gridgain-sink-node:
    image: gridgain/enterprise:8.7.14
    container_name: gridgain-sink-node
    tty: true
    environment:
      - "JVM_OPTS=-DIGNITE_QUIET=true -Xmx1G"
      - CONFIG_URI=/opt/gridgain/ext-config/gridgain-sink-config.xml
      - OPTION_LIBS=ignite-rest-http
      - IGNITE_QUIET=false
    networks:
      - gridgain-net
#    command: 'cp /opt/gridgain/extra-jars/* /opt/gridgain/libs/ && sleep infinity'
    ports:
      #- "31100-31200"
      #- "11211"
      #- "49128"
      #- "47500-47600"
      #- "47100-47200"
      #- "48100-48200"
#      - "47502:47500"
#      - "47102:47100"
      - "10801:10800"
      - "6082:8080"
    volumes:
      #      - gridgain-data-2:/opt/gridgain/work
      - ./gridgain-config:/opt/gridgain/ext-config

  kafka:
    image: gridgain-kafka-image
    build: ./gridgain-kafka-image
    container_name: gridgain-kafka
    restart: always
    tty: true
#    volumes:
#      - "./kafka-scripts:/scripts"
    ports:
      # Broker
      - "9092:9092"
      # ZK
      - "2181:2181"
      # Kafka Manager UI
      - "3030:3030"
      # REST API, Schema registry & Kafka- Connect Ports
      - "8081-8083:8081-8083"
      # JMX and other monitoring ports
      - "9581-9585:9581-9585"
    volumes:
      - ./gridgain-kafka-image/conf:/conf
    depends_on:
      - gridgain-sink-node
      - gridgain-source-node
    networks:
      - gridgain-net

  backend:
    image: gridgain/gridgain-web-console-backend:2020.03.01
    # Restart on crash.
    restart: always
    tty: true
    container_name: gridgain-webconsole-backend
    volumes:
      - ./gridgain-console-work:/opt/gridgain-web-console-server/work
    networks:
      - gridgain-net

  frontend:
    image: gridgain/gridgain-web-console-frontend:2020.03.01
    container_name: gridgain-webconsole-frontend
    tty: true
    depends_on:
      - backend
    networks:
      - gridgain-net
    ports:
      # Proxy HTTP nginx port (HOST_PORT:DOCKER_PORT)
      - 80:8008
networks:
  gridgain-net:
    driver: bridge
